module Character
  CHARACTER_QUOTE_HASH =
  {
    "Rick Grimes" => ["You don\'t know what it\'s like out there.\nYou may think you do but you don\'t.",
                      "There\'s us and the dead. We survive this by pulling together, not apart.",
                      "We don't kill the living."],
    "Lori Grimes" => ["Look at me. Do I look worried?",
                      "We\'re ready.",
                      "We\'ll build a fire, yeah?"],
    "Shane Walsh" => ["Just shut up and give me the guns!",
                      "These things ain\'t sick. They\'re not people. They\'re dead.\nAin\'t gonna feel nothing for them \'cause all they do, they kill!",
                      "You just can\'t be a good guy and expect to live. Not anymore."],
    "Dale Horvath" => ["I know what kind of man you are.",
                       "We know what\'s waiting for us out there. I don\'t want to face it alone.",
                       "Too bad. See, you don\'t get to do that, to come into somebody\'s life, make them care and just check out.\nI\'m staying. The matter is settled."],
    "Daryl Dixon" => ["You gonna take 'em all on? How many Walkers have you killed?",
                      "All right. It\'s as good a night as any.",
                      "Stay off the main roads.\nThe bigger the roads, the more Walkers, more assholes like this one.\nI got him."],
    "Glenn Rhee" => ["Admit it. You only came back to Atlanta for the hat.",
                     "I\'m Korean.",
                     "We actually know what we\'re doing out there."],
    "Maggie Greene" => ["We\'re gonna make it. Both of us, we will. That\'s the hard part.",
                        "I don\'t want to be afraid of being alive.",
                        "It\'s not like our options are vast these days."],
    "Michonne" => ["I came out here to help.",
                   "You think I was gonna let you go in there?",
                   "I can\'t stop you. But you can\'t stop me from helping you."],
    "The Governor" => ["Come on, let\'s play.",
                       "In this life now you kill or you die. Or you die and you kill.",
                       "There are people I need to keep alive."],
    "Hershel Greene" => ["We have guns. We have cars.",
                         "I just met you. At least buy me a drink first.",
                         "Nah, I can shoot. Just don\'t like to."]
  }

  CHARACTER_WIN_HASH =
  {
    "Rick Grimes" => ["We left him like an animal caught in a trap",
                      "That is my unborn child. I will stay alive to keep them alive.",
                      "Isn\'t that enough? I\'m still here."],
    "Lori Grimes" => ["I did what needed to be done.",
                      "We were ready.",
                      "I did what I had to do to keep this group safe and do it with a clear conscience."],
    "Shane Walsh" => ["A little boy lived because of what went down that night. I think you oughta show some gratitude.",
                      "One of us wasn\'t gonna make it out. It had to be him.",
                      "You and me man, we\'ll be heroes."],
    "Dale Horvath" => ["I had it fixed yesterday.",
                       "I know you\'re angry at me. That much is clear.\nBut if I hadn\'t done what I did, you\'d be dead now.",
                       "At least I can say when the world goes to shit, I didn\'t let it take me down with it."],
    "Daryl Dixon" => ["I ain\'t nobody\'s bitch.",
                      "If it\'s smart it left the country. Thing almost got me killed.",
                      "Toughest asshole I ever met, my brother. Feed him a hammer, he'd crap out nails."],
    "Glenn Rhee" => ["When I found out about the zombies in the barn, I told, for the good of everyone.",
                      "Time to deliver some pizzas.",
                      "Piece of cake."],
    "Michonne" => ["Now that we can take a breath...",
                   "That\'s \'cause I could see it.",
                   "You wanna end up on your ass again?"],
    "The Governor" => ["It isn\'t personal",
                       "You smell the gunpowder and you see the blood. It means you\'re alive. It means you won.\nYou take the heads so that you don\'t ever forget.",
                       "You can lose a lot of soldiers but still win the game."],
    "Hershel Greene" => ["Beautiful",
                         "Any idea hat happened to my horse?",
                         "Saved my life. Gave me more time with my girls.\nGave me more time with my brother. Can\'t put a price on that."]
  }

  CHARACTER_LOSE_HASH =
  {
    "Rick Grimes" => ["You thought there was a cure. You can\'t blame yourself for holding out for hope.",
                      "We\'re all infected.",
                      "I didn\'t have enough ammo."],
    "Lori Grimes" => ["I would rather eat Miss piggy. Yes, that came out wrong.",
                      "You were right, I\'m sorry.",
                      "We need to talk..."],
    "Shane Walsh" => ["Just shut up.",
                      "Eh. Yeah. That\'s what it\'s gonna take.",
                      "Fair enough."],
    "Dale Horvath" => ["Are you serious?",
                       "Well, don\'t be too hard on yourself.",
                       "Well, if I\'d been informed of the coming apocalypse I\'d have stocked up."],
    "Daryl Dixon" => ["Come on, I ain\'t got all day.",
                      "What are you braying at, jackass?",
                      "That\'s the third time you\'re pointing that thing at my head.\nYou gonna pull the trigger or what?"],
    "Glenn Rhee" => ["How long do any of us have?",
                     "Yeah, pretty sure you got that backwards.",
                     "What the hell was that?"],
    "Michonne" => ["This place is not what they say it is.",
                   "This isn\'t the world. This isn\'t it.",
                   "That\'s giving up."],
    "The Governor" => ["The roads. The biters.",
                       "I told you to kill her but you didn\'t. And now you gonna turn and you gonna tear away the flesh of her bones.",
                       "Due to your lack of insight. You failed to see the devil beside you."],
    "Hershel Greene" => ["There is no hope for any of us.",
                         "I\'m a ghost from the knee down.",
                         "This is my farm. I\'ll die here."]
  }

  DRAW_HASH =
  {
    "Rick Grimes" => ["Maybe we got a second chance. Not many people get that.",
                      "Go on, there\'s the door. You can do better, let\'s see how far you get.",
                      "No! Stop it!"],
    "Lori Grimes" => ["Maybe there\'s nothing to talk about anymore.",
                      "You\'re not a killer and I know that.",
                      "What\'s the matter with you? Why would you be so selfish?"],
    "Shane Walsh" => ["I don\'t think a nail file\'s gonna do it.",
                      "When you get down to that last can of beans, you\'re gonna be loving those frog legs.",
                      "How\'s that?"],
    "Dale Horvath" => ["He\'ll be fine. How about you?",
                       "I don\'t know what to say",
                       "Am I gonna have to shoot you? Do I have to kill you? Is that what it\'s gonna take?"],
    "Daryl Dixon" => ["What do you want?",
                      "Herd that size\'ll rip the house down.",
                      "Yeah, and people in hell want Slurpees."],
    "Glenn Rhee" => ["He left the building. Why the hell would he do that?",
                     "Good one.",
                     "Maybe they\'ll just pass like the herd on the highway. Should we just go inside?"],
    "Michonne" => ["No. And no more bullshit. You wait here. That\'s how we get it done.",
                   "I was gonna go back in anyway.",
                   "Something\'s gonna happen. Just don\'t make something happen."],
    "The Governor" => ["You can\'t think forever. Sooner or later you have to make a move.",
                       "Remember, if it gets tough out there, you\'re always welcome here.",
                       "No way we can live side by side."],
    "Hershel Greene" => ["You've got to get your family to safety. I know a few places. We\'ll meet up at one of them later.",
                         "We\'ll find a way.",
                         "I\'m not showing you my leg."]
    }
end
